[window]
padding = { x = 5, y = 0 }
dynamic_padding = true
decorations = "Full"
opacity = 0.95
blur = true
startup_mode = "Maximized"
# startup_mode = "Windowed"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Thin"}
bold = { family = "JetBrainsMono Nerd Font Mono", style = "ExtraLight"}
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Thin Italic"}
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "ExtraLight Italic"}
offset = { x = 1, y = 1 }
# normal = { family = "PlemolJP35 Console NF", style = "Light"}
# bold = { family = "PlemolJP35 Console NF", style = "Regular"}
# italic = { family = "PlemolJP35 Console NF", style = "Light Italic"}
# bold_italic = { family = "PlemolJP35 Console NF", style = "Regular Italic"}
# offset = { x = 1, y = 5 }
size = 11.5
# size = 12.0

[selection]
save_to_clipboard = true

[cursor]
style = "Underline"

# Colors (Rose-Pine)
# [colors.primary]
# background = '#191724'
# foreground = '#e0def4'
#
# [colors.cursor]
# text = '#e0def4'
# cursor = '#524f67'
#
# [colors.vi_mode_cursor]
# text = '#e0def4'
# cursor = '#524f67'
#
# [colors.selection]
# text = '#e0def4'
# background = '#403d52'
#
# [colors.normal]
# black = '#26233a'
# red = '#eb6f92'
# green = '#31748f'
# yellow = '#f6c177'
# blue = '#9ccfd8'
# magenta = '#c4a7e7'
# cyan = '#ebbcba'
# white = '#e0def4'
#
# [colors.bright]
# black = '#6e6a86'
# red = '#eb6f92'
# green = '#31748f'
# yellow = '#f6c177'
# blue = '#9ccfd8'
# magenta = '#c4a7e7'
# cyan = '#ebbcba'
# white = '#e0def4'
#
# [colors.hints]
# start = {foreground = '#908caa', background = '#1f1d2e' }
# end = { foreground = '#6e6a86', background = '#1f1d2e' }

# Colors (Base16 Default Dark)
[colors.primary]
background = '#181818'
foreground = '#d8d8d8'

[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

# Normal colors
[colors.normal]
black   = '#181818'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
# blue    = '#7cafc2'
blue    = '#81a1c1'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'

# Bright colors
[colors.bright]
black   = '#585858'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#f8f8f8'
