[shell]
program = "/Windows/System32/wsl.exe"
args = ["-d Ubuntu"]

[window]
padding = { x = 6, y = 6 }
opacity = 1.0
startup_mode = "Maximized"

[font]
normal = { family = "PlemolJP35 Console NF", style = "Regular"}
bold = { family = "PlemolJP35 Console NF", style = "SemiBold"}
italic = { family = "PlemolJP35 Console NF", style = "Italic"}
bold_italic = { family = "PlemolJP35 Console NF", style = "SemiBold Italic"}
size = 10.0   # 200% old-9.75
#size = 10.75  # 175%
offset = { x = 1, y = 1 }

# [colors]
# [colors.primary]
# background = "#2E3440"

[selection]
save_to_clipboard = true
