[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.95
blur = true
startup_mode = "Windowed"

[font]
normal = { family = "PlemolJP35 Console NF", style = "Light"}
bold = { family = "PlemolJP35 Console NF", style = "Rgular"}
italic = { family = "PlemolJP35 Console NF", style = "Light Italic"}
bold_italic = { family = "PlemolJP35 Console NF", style = "Italic"}
size = 12.5
offset = { x = 1, y = 4 }

[selection]
save_to_clipboard = true

