# Theme color - macOS
# [[plugins]]
# repo = 'cocopon/iceberg.vim'
# hook_add = """
# source $HOME/.cache/dein/repos/github.com/cocopon/iceberg.vim/colors/iceberg.vim
# """

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = """
colorscheme nord
"""

# [[plugins]]
# repo = 'morhetz/gruvbox'
# hook_add = """
# source $HOME/.cache/dein/repos/github.com/morhetz/gruvbox/colors/gruvbox.vim
# """

# [[plugins]]
# repo = 'EdenEast/nightfox.nvim'
# hook_add = """
# colorscheme nightfox
# """
