#--- Python ---#
[[plugins]]
repo = 'vim-python/python-syntax'
on_ft = ['python']
hook_add = """
let g:python_highlight_all = 1
"""

[[plugins]]
# Workaround (21.11.15)
# Python indentation does not work properly due to a bug(?) in neovim.
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo='pixelneo/vim-python-docstring'
on_ft = ['python']

#--- Javascript etc ---#
[[plugins]]
repo = 'yuezk/vim-js'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']
hook_add = """
let g:vim_jsx_pretty_colorful_config = 1
"""

#--- Svelte ---#
# [[plugins]]
# repo = 'leafOfTree/vim-svelte-plugin'
# on_ft = ['svelte']
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['svelte']

[[plugins]]
repo = 'evanleck/vim-svelte'
depends = ['vim-javascript']
on_ft = ['svelte']
hook_add = """
let g:svelte_indent_script = 0
let g:svelte_indent_style = 0
"""

#--- Toml ---#
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#--- Markdown ---#
[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_ft = ['markdown']
hook_add = """
let g:preview_markdown_parser = 'glow'
"""

#--- Debug ---#
# execute :VimspectorInstall for the 1st time.
[[plugins]]
repo = 'puremourning/vimspector'
on_ft = ['python', 'go', 'javascript']
hook_add = """
let g:vimspector_enable_mappings = 'HUMAN'
let g:vimspector_install_gadgets = ['debugpy', 'vscode-go', 'vscode-node-debug2']
"""

#--- Test runner ---#
[[plugins]]
repo = 'janko-m/vim-test'
on_ft = ['python']
hook_add = """
let g:test#strategy = 'neovim'
let g:test#python#runner = 'pytest'
"""
