# Theme color - macOS
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = """
source $HOME/.cache/dein/repos/github.com/cocopon/iceberg.vim/colors/iceberg.vim
"""

# [[plugins]]
# repo = 'ayu-theme/ayu-vim'
# hook_add = """
# let g:ayucolor = 'dark'
# colorscheme ayu
# """

# [[plugins]]
# repo = 'EdenEast/nightfox.nvim'
# hook_add = """
# colorscheme nightfox
# """
