# Required!!
# How to update plugins -> :call dein#check_update(v:true)
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = """
"""

# Icon display on defx
[[plugins]]
repo = 'kristijanhusak/defx-icons'
hook_add = """
let g:defx_icons_enable_syntax_highlight = 0
let g:defx_icons_column_length = 2
"""
# Git display on defx
[[plugins]]
repo = 'kristijanhusak/defx-git'
# File explorer - defx
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source $HOME/.config/nvim/plugins/defx.rc.vim
let g:python3_host_prog = '$HOME/.pyenv/shims/python3'
"""

# Brackets
[[plugins]]
repo = 'jiangmiao/auto-pairs'
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = """
let g:closetag_filenames = '*.html,*.js,*.jsx,*.ts,*.tsx,*.vue,*.svelte'
let g:closetag_emptyTags_caseSensitive = 1
"""
[[plugins]]
repo = 'tpope/vim-surround'

# Cursor
[[plugins]]
repo = 'skanehira/jumpcursor.vim'
[[plugins]]
repo = 't9md/vim-quickhl'

# Comment
[[plugins]]
repo = 'tpope/vim-commentary'

# fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'rbong/vim-flog'

# UI
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = """
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#tabline#tab_nr_type = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#extensions#branch#enabled = 1
let g:airline_powerline_fonts = 1
"""
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = 0
hook_add = """
source $HOME/.config/nvim/plugins/coc.rc.vim
"""

# Snippet
[[plugins]]
repo = 'sirver/ultisnips'
hook_add = """
let g:UltiSnipsExpandTrigger='<Nop>'
let g:UltiSnipsJumpForwardTrigger='<Nop>'
let g:UltiSnipsJumpBackwardTrigger='<Nop>'
let g:ultisnips_python_style = 'google'
"""
