#--- Syntax highlight ---#
#--- Svelte ---#
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['svelte']
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['svelte']
[[plugins]]
repo = 'evanleck/vim-svelte'
depends = ['vim-javascript', 'html5.vim']
on_ft = ['svelte']
hook_add = """
let g:svelte_indent_script = 0
let g:svelte_indent_style = 0
"""

#--- Plugins for languages ---#
#--- Python ---#
[[plugins]]
repo='pixelneo/vim-python-docstring'
on_ft = ['python']

#--- Markdown ---#
[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_ft = ['markdown']
hook_add = """
let g:preview_markdown_parser = 'glow'
"""

#--- Debug ---#
# execute :VimspectorInstall for the 1st time.
[[plugins]]
repo = 'puremourning/vimspector'
on_ft = ['python', 'go', 'javascript', 'typescript']
hook_add = """
let g:vimspector_enable_mappings = 'HUMAN'
let g:vimspector_install_gadgets = ['debugpy', 'delve', 'vscode-node']
"""

#--- Test runner ---#
[[plugins]]
repo = 'janko-m/vim-test'
on_ft = ['python', 'go']
hook_add = """
let g:test#strategy = 'neovim'
let g:test#python#runner = 'pytest'
let g:test#go#runner = 'gotest'
"""
