alias ll='eza -al'
alias ld='eza -al -s new'
alias lt='eza --icons -T -L 2 -al'
alias lls='eza -al -s size'
alias cl='clear'
alias vim='nvim.appimage'
alias view='nvim.appimage -R'

alias g='git'
alias ga='git add .'
alias gb='git branch'
alias gc='git commit -m $1'
alias gk='git checkout -b $1'
alias gl='git log --graph --oneline'
alias gp='git pull'
alias gs='git status -sb'
alias doc='docker'
alias dcc='docker compose'

alias tm1='tmux new-session\; source-file ~/dotfiles/tmux/.tmux.session1.conf'
alias tm2='tmux new-session\; source-file ~/dotfiles/tmux/.tmux.session2.conf'
alias tm3='tmux new-session\; source-file ~/dotfiles/tmux/.tmux.session3.conf'
