alias ll='eza -al'
alias ld='eza -al -s new'
alias lt='eza --icons -T -L 3 -al'
alias lls='exa -al -s size'
alias cl='clear'
alias vim='nvim'
alias view='nvim -R'

alias g='git'
alias ga='git add .'
alias gb='git branch'
alias gc='git commit -m $1'
alias gk='git checkout -b $1'
alias gl='git log --graph --oneline'
alias gp='git pull'
alias gs='git status -sb'
alias cz="czg"
alias lg='lazygit'
alias pr='cd (git rev-parse --show-toplevel)'

alias bu='brew upgrade'
alias bc='brew cleanup'
alias doc='docker'
alias dcc='docker compose'

alias dev='cd ~/Develop'
alias mdev='cd ~/Develop/Project'
alias cld='cd /Users/nnamm/Library/Mobile\ Documents/com~apple~CloudDocs/'
alias tm1='tmux new-session\; source-file ~/dotfiles/tmux/.tmux.session1.conf'
alias tm2='tmux new-session\; source-file ~/dotfiles/tmux/.tmux.session2.conf'
alias tm3='tmux new-session\; source-file ~/dotfiles/tmux/.tmux.session3.conf'
