alias ll='exa -al'
alias ld='exa -al -s new'
alias lls='exa -al -s size'
alias cl='clear'
alias vim='nvim.appimage'
alias view='nvim.appimage -R'

alias g='git'
alias ga='git add .'
alias gb='git branch'
alias gc='git commit -m $1'
alias gp='git pull'
alias gs='git status'

alias dev='cd ~/work'
alias mdev='cd /media/psf/parallels'
alias tm1='tmux new-session\; source-file ~/dotfiles/tmux/.tmux.session1.conf'
alias tm2='tmux new-session\; source-file ~/dotfiles/tmux/.tmux.session2.conf'
alias tm3='tmux new-session\; source-file ~/dotfiles/tmux/.tmux.session3.conf'
