
[tool.black]
target-version = ['py3xx']
line-length = 88

[tool.flake8]
max-line-length = 88
max-complexity = 20
extend-ignore = [
    "W503", "W504",
]

[tool.isort]
profile = "black"
multi_line_output = 7
force_single_line = true
line_length = 88

[tool.mypy]
python_version = "3.xx"
ignore_missing_imports = true
#[[tool.mypy.overrides]]

[tool.pylint.messages_control]
max-line-length = 88
