
[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88
max-complexity = 20
extend-ignore = [
    "W503", "W504",
    "E203"
]

[tool.pylint.messages_control]
max-line-length = 88

[tool.isort]
profile = "black"
# multi_line_output = 3
# include_trailing_comma = "True"
# force_grid_wrap = 0
# use_parentheses = "True"
# ensure_newline_before_comments = "False"
# line_length = 88
